/* tslint:disable */
/* eslint-disable */
/**
 * OneVoice Backend API
 * AI-powered video dubbing service backend API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@onevoice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

