"""add dubbing fields to videos table

Revision ID: c6c771a8b1b1
Revises: e934d65f7db0
Create Date: 2025-08-10 12:13:11.142933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c771a8b1b1'
down_revision: Union[str, None] = 'e934d65f7db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('videos', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('videos', sa.Column('dubbed_video_path', sa.String(length=500), nullable=True))
    op.add_column('videos', sa.Column('subtitle_video_path', sa.String(length=500), nullable=True))
    op.add_column('videos', sa.Column('dub_subtitles_path', sa.String(length=500), nullable=True))
    op.add_column('videos', sa.Column('translation_subtitles_path', sa.String(length=500), nullable=True))
    op.add_column('videos', sa.Column('source_subtitles_path', sa.String(length=500), nullable=True))
    op.add_column('videos', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'completed_at')
    op.drop_column('videos', 'source_subtitles_path')
    op.drop_column('videos', 'translation_subtitles_path')
    op.drop_column('videos', 'dub_subtitles_path')
    op.drop_column('videos', 'subtitle_video_path')
    op.drop_column('videos', 'dubbed_video_path')
    op.drop_column('videos', 'file_path')
    op.drop_column('videos', 'original_filename')
    # ### end Alembic commands ###