"""drop legacy video path columns

Revision ID: 00d3052edb4b
Revises: c6c771a8b1b1
Create Date: 2025-08-10 12:52:52.080939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d3052edb4b'
down_revision: Union[str, None] = 'c6c771a8b1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'translation_subtitles_path')
    op.drop_column('videos', 'dub_subtitles_path')
    op.drop_column('videos', 'processed_file_path')
    op.drop_column('videos', 'file_path')
    op.drop_column('videos', 'dubbed_video_path')
    op.drop_column('videos', 'source_subtitles_path')
    op.drop_column('videos', 'original_filename')
    op.drop_column('videos', 'original_file_path')
    op.drop_column('videos', 'subtitle_video_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('subtitle_video_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('original_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('source_subtitles_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('dubbed_video_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('processed_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('dub_subtitles_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('translation_subtitles_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###