"""add weight column to job_steps for weighted progress

Revision ID: d3cbef54e357
Revises: e365929f9aa0
Create Date: 2025-08-19 11:13:58.050634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cbef54e357'
down_revision: Union[str, None] = 'e365929f9aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_steps', sa.Column('weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_steps', 'weight')
    # ### end Alembic commands ###