"""migrate_stripe_to_paddle

Revision ID: 4c0d3d3eb9ed
Revises: d3cbef54e357
Create Date: 2025-09-02 11:15:16.684734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0d3d3eb9ed'
down_revision: Union[str, None] = 'd3cbef54e357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_history', sa.Column('paddle_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('billing_history', sa.Column('paddle_subscription_id', sa.String(length=100), nullable=True))
    op.add_column('billing_history', sa.Column('paddle_invoice_id', sa.String(length=100), nullable=True))
    op.add_column('billing_history', sa.Column('payment_provider', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('billing_history_stripe_invoice_id_key'), 'billing_history', type_='unique')
    op.create_unique_constraint(None, 'billing_history', ['paddle_transaction_id'])
    op.drop_column('billing_history', 'stripe_payment_intent_id')
    op.drop_column('billing_history', 'stripe_charge_id')
    op.drop_column('billing_history', 'stripe_invoice_id')
    op.add_column('subscriptions', sa.Column('paddle_subscription_id', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', type_='unique')
    op.create_unique_constraint(None, 'subscriptions', ['paddle_subscription_id'])
    op.drop_column('subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.create_unique_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('subscriptions', 'paddle_subscription_id')
    op.add_column('billing_history', sa.Column('stripe_invoice_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('billing_history', sa.Column('stripe_charge_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('billing_history', sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'billing_history', type_='unique')
    op.create_unique_constraint(op.f('billing_history_stripe_invoice_id_key'), 'billing_history', ['stripe_invoice_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('billing_history', 'payment_provider')
    op.drop_column('billing_history', 'paddle_invoice_id')
    op.drop_column('billing_history', 'paddle_subscription_id')
    op.drop_column('billing_history', 'paddle_transaction_id')
    # ### end Alembic commands ###