"""move_video_fields_to_media_files

Revision ID: e365929f9aa0
Revises: 229dcddbe0ea
Create Date: 2025-08-10 13:54:29.842250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e365929f9aa0'
down_revision: Union[str, None] = '229dcddbe0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('media_files', sa.Column('resolution', sa.String(length=20), nullable=True))
    op.add_column('media_files', sa.Column('fps', sa.Float(), nullable=True))
    op.drop_column('videos', 'thumbnail_url')
    op.drop_column('videos', 's3_key')
    op.drop_column('videos', 'resolution')
    op.drop_column('videos', 'format')
    op.drop_column('videos', 's3_bucket')
    op.drop_column('videos', 'duration')
    op.drop_column('videos', 'extra_metadata')
    op.drop_column('videos', 'file_size')
    op.drop_column('videos', 'fps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('fps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('s3_bucket', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('format', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('resolution', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('s3_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('media_files', 'fps')
    op.drop_column('media_files', 'resolution')
    op.drop_column('media_files', 'duration')
    # ### end Alembic commands ###