"""Remove celery_task_id column from jobs table

Revision ID: 96dfaf4e857b
Revises: 3cc96bfb8132
Create Date: 2025-08-03 16:09:29.536173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dfaf4e857b'
down_revision: Union[str, None] = '3cc96bfb8132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jobs_celery_task_id_key'), 'jobs', type_='unique')
    op.drop_column('jobs', 'celery_task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('celery_task_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('jobs_celery_task_id_key'), 'jobs', ['celery_task_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###