# coding: utf-8

"""
    OneVoice Backend API

    AI-powered video dubbing service backend API

    The version of the OpenAPI document: 1.0.0
    Contact: support@onevoice.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.authentication_api import router as AuthenticationApiRouter
from openapi_server.apis.billing_subscriptions_api import router as BillingSubscriptionsApiRouter
from openapi_server.apis.user_management_api import router as UserManagementApiRouter
from openapi_server.apis.video_management_api import router as VideoManagementApiRouter

app = FastAPI(
    title="OneVoice Backend API",
    description="AI-powered video dubbing service backend API",
    version="1.0.0",
)

app.include_router(AuthenticationApiRouter)
app.include_router(BillingSubscriptionsApiRouter)
app.include_router(UserManagementApiRouter)
app.include_router(VideoManagementApiRouter)
